# Generated by Django 5.0.6 on 2024-05-08 04:04

import ckeditor.fields
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
