# Generated by Django 5.0.6 on 2024-05-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foods.menuitem'),
        ),
        migrations.AlterField(
            model_name='likestore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.store'),
        ),
    ]
