# Generated by Django 5.0.6 on 2024-05-22 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_likemenuitem_menu_item_alter_likestore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
