# Generated by Django 4.2.13 on 2024-06-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_user_user_latitude_user_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
