# Generated by Django 5.0.6 on 2024-05-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_store_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='followers',
        ),
    ]
