# Generated by Django 4.2.13 on 2024-06-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_store_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
    ]
