# Generated by Django 5.0.6 on 2024-05-08 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_comment_rating_comment_store_like_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foods.store'),
        ),
    ]
