# Generated by Django 4.2.13 on 2024-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_store_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_latitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_longitude',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
