# Generated by Django 4.2.13 on 2024-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_user_user_latitude_alter_user_user_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_latitude',
            field=models.CharField(default='10.765505130395395', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_location',
            field=models.CharField(default='Quan 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_longitude',
            field=models.CharField(default='106.68168869289711', max_length=255, null=True),
        ),
    ]
