# Generated by Django 5.0.6 on 2024-05-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_comment_rating_alter_commentstore_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.menuitem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.store'),
        ),
    ]
