# Generated by Django 5.0.6 on 2024-05-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_comment_menu_item_alter_comment_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstore',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foods.store'),
        ),
    ]
