# Generated by Django 5.0.6 on 2024-05-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_comment_menu_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='ReviewMenuItem',
        ),
        migrations.RenameModel(
            old_name='CommentStore',
            new_name='ReviewStore',
        ),
    ]
