# Generated by Django 5.0.6 on 2024-05-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_likemenuitem_store_reviewmenuitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
