# Generated by Django 5.0.6 on 2024-05-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_commentmenuitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentMenuItem',
            new_name='Comment',
        ),
    ]
