# Generated by Django 5.0.6 on 2024-05-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_rename_commentmenuitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foods.menuitem'),
        ),
    ]
